language: node_js
node_js:
  - '12'

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

notifications:
  email: false

script:
  - yarn run fmt --check
  - yarn run tsc --noEmit
  - yarn run test:ci

branches:
  only: master
