// flow-typed signature: 9f92c40f24f89d198e0bdd56e5559401
// flow-typed version: <<STUB>>/eslint-config-precure_v^0.4.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-precure'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-precure' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-precure/index' {
  declare module.exports: $Exports<'eslint-config-precure'>;
}
declare module 'eslint-config-precure/index.js' {
  declare module.exports: $Exports<'eslint-config-precure'>;
}
