// flow-typed signature: 9d0d5d36a727e913cc9b98b990b399bb
// flow-typed version: <<STUB>>/extract-react-intl_v^0.1.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-react-intl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-react-intl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'extract-react-intl/index' {
  declare module.exports: $Exports<'extract-react-intl'>;
}
declare module 'extract-react-intl/index.js' {
  declare module.exports: $Exports<'extract-react-intl'>;
}
