// flow-typed signature: 9f704a8b4dfad3a54e3fe0e7c036e7f9
// flow-typed version: <<STUB>>/read-babelrc-up_v^0.1.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'read-babelrc-up'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'read-babelrc-up' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'read-babelrc-up/index' {
  declare module.exports: $Exports<'read-babelrc-up'>;
}
declare module 'read-babelrc-up/index.js' {
  declare module.exports: $Exports<'read-babelrc-up'>;
}
