// flow-typed signature: 70ed45b6604fb288a23b7e391b226e70
// flow-typed version: <<STUB>>/sort-keys_v^1.1.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sort-keys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sort-keys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'sort-keys/index' {
  declare module.exports: $Exports<'sort-keys'>;
}
declare module 'sort-keys/index.js' {
  declare module.exports: $Exports<'sort-keys'>;
}
