// flow-typed signature: 05568ad0e241f0a220735adacab93cea
// flow-typed version: <<STUB>>/write-json-file_v^2.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'write-json-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'write-json-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'write-json-file/index' {
  declare module.exports: $Exports<'write-json-file'>;
}
declare module 'write-json-file/index.js' {
  declare module.exports: $Exports<'write-json-file'>;
}
